### ISSUE TITLE
Migrate to robotology

### ISSUE THREAD

**Issue by traversaro** [robotology/osqp-eigen#2]
Ad discussed with @GiulioRomualdi and @S-Dafarra, it would be useful to move this repo to robotology . 
For this, we should rename the repo to have a name compliant to robotology organization style. 
@GiulioRomualdi let me know when you are ready to move (note that GitHub handles renaming quite well, so this should not be problematic in any way).

cc @DanielePucci

**Comment by GiulioRomualdi** [comment]
Ok, as regarding the name of the repo what do you prefer?
1. osqp-c++;
2. osqp-eigen;
3. osqp-c++-eigen;
4. ...

**Comment by traversaro** [comment]
I think `osqp-eigen` is the most descriptive one, if you want to have `c++` in the name I would go for `cxx` or `cpp` to avoid strange corner-case problems with having `+` in the package/repo name.

**Comment by traversaro** [comment]
The `osqp-something` naming scheme is also compatible with the names of the repositories of osqp bindings for Python, Fortran and MATLAB: https://github.com/oxfordcontrol .

Once you are a bit confident that the API interface is stable (ish), you could propose to OSQP's authors to include the link to this Eigen interface to OSQP in the OSQP Interfaces page: http://osqp.readthedocs.io/en/latest/interfaces/ (there are already some 3rd-party interfaces such as cutest).

**Comment by GiulioRomualdi** [comment]
Ok the name of the repository will be change into `osqp-eigen`. The `master` branch is fully tested while, in the next few days, I will write some tests for the `devel_update_matrices` branch.

**Comment by S-Dafarra** [comment]
Maybe when migrating we could change ``Optimizator*`` to ``Optimizer*`` :wink: .

**Comment by GiulioRomualdi** [comment]
> Maybe when migrating we could change Optimizator* to Optimizer* :wink: .

Done! :smile:

**Comment by GiulioRomualdi** [comment]
Porting can be performed when [this issue](https://github.com/loc2/component_wholebody-teleoperation/issues/88) will be closed.

**Comment by ahoarau** [comment]
@traversaro You are everywhere I look ! :smiley: 

Question : Isn't the default licensing for robotology LGPLv2-3 ? I'd like to use this but not put my code GPL

**Comment by traversaro** [comment]
Hi @ahoarau !
Yep the software is licensed under LGPL2/3, the content of the LICENSE file will be changed soon, thanks for pointing that out.

**Comment by S-Dafarra** [comment]
Just a couple of suggestion before migrating to robotology.
Maybe it is better to rename the files from ``Optimizer*`` to ``OsqpEigen*``, to make clearer the inclusion of these files in external projects. In addition the name ``OptimizerSolver`` seems a repetition. 
Another option could be to remove ``Optimizer*`` from the file name and place them all in a folder called ``OsqpEigen``, so that the inclusion would seem like:
```cxx
#include <OsqpEigen/Solver.hpp>
```
instead of 
```cxx
#include <OptimizerSolver.hpp>
```

I would suggest also to change the name of the namespace from ``OsqpWrapper`` to ``OsqpEigen`` to preserve consistency with the project name.

I can deal with these modification if you like, maybe adding them to https://github.com/GiulioRomualdi/osqp-eigen/pull/5.

Clearly this would break the code which has been written according to the current version, but it may be reasonable to change it when migrating organization.

**Comment by GiulioRomualdi** [comment]
Since #5  and #7 were merged are the license was updated (now LGPL 3) we can move this repository to robotology. 
@DanielePucci @S-Dafarra @traversaro

**Comment by GiulioRomualdi** [comment]
I think we can close this issue.

**Comment by traversaro** [comment]
Yeah!
