### ISSUE TITLE
Unexplained error "upper bound must be greater than or equal to lower bound"

### ISSUE THREAD

**Issue by stribor14** [robotology/osqp-eigen#26]
I know what error means, but I don't know why it's happening.
Here is an example of my up/lo bounds (they are a lot bigger than this example but somewhat similar in composition). In a class constructor, I prepare two matrices and fill them with data that is constant (`RES` = reserved for later):
```
lo_bound = [RES, RES, 0, 0, -pi/2, -inf, -inf, -pi/2]
up_bound = [RES, RES, 0, 0,  pi/2,  inf,  inf,  pi/2]
```

Before every new solving step, I update `RES` to the current condition. Identical values in both bounds, for example, let's say:
```
lo_bound = [0.2, -1.4, 0, 0, -pi/2, -inf, -inf, -pi/2]
up_bound = [0.2, -1.4, 0, 0,  pi/2,  inf,  inf,  pi/2]
```

After that, I call:
```
  solver.updateLowerBound(lo_bound_);
  solver.updateUpperBound(up_bound_);
```

And in every step, I get the same error, even though every value in `up_bound` is equal or greater than `lo_bound` (I even update `lo_bound` before `up_bound`, so it cannot say that new `up_bound` is lower than previous `lo_bound`)

If it's needed, I can paste here real lo/up bounds from my app

**Comment by S-Dafarra** [comment]
Hello @stribor14!

Notice that the error you are mentioning is actually thrown by ``osqp`` itself, in particular, in these two lines:
- https://github.com/oxfordcontrol/osqp/blob/7b33ad2c0aac71bdfc107a2ca139ee67c9addde6/src/osqp.c#L802
- https://github.com/oxfordcontrol/osqp/blob/7b33ad2c0aac71bdfc107a2ca139ee67c9addde6/src/osqp.c#L856.

My guess is that when you are updating the bounds, you are doing it using two separate calls, namely ``solver.updateLowerBound`` and ``solver.updateUpperBound``. Since these bounds seem to depend on the variable ``RES``, if you update first the lower bound with a value of ``RES`` bigger than the previous one, that error will be thrown. Indeed, ``osqp`` does not know that you are just about to change also the upper bound. Even if you invert the order, it may still happen that the new value of ``RES`` is (slightly) *smaller* than the old one.
A possible fix could be to call the method [``updateBounds``](https://github.com/robotology/osqp-eigen/blob/7109a226f0cc6dd7d01eb912561e9a0e9eb1d57a/include/OsqpEigen/Solver.tpp#L72) instead, where both the upper bound and the lower bound are set at the same time.

Let me know if that works!

**Comment by stribor14** [comment]
Thank you for your reply! Calling the update through `updateBounds` fixed the problem. I think this can be closed since it's not really an issue.

I had the same reasoning as you for why this message could be happening, but now looking at their (osqp) code, I see the source of my confusion. When updating the lower bound you get a message "Upper bound must ..." and vice versa, which is a bit ambiguous (misleading even) about which bound is problematic :)
